spring:
  datasource:
    url: jdbc:mysql://localhost:3310/advancedev
    username: devuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect